version: "3.8"
services:
  aphrodite:
    volumes:
    - ./visualization_utils.py:/app/COVIDNet-CT/visualization_utils.py
    - ./run_covidnet_ct.py:/app/COVIDNet-CT/run_covidnet_ct.py
    - ./utils.py:/app/COVIDNet-CT/utils.py
    - ./read_dicom.py:/app/COVIDNet-CT/read_dicom.py
    - ./main.py:/app/COVIDNet-CT/main.py
    - ./assets:/app/COVIDNet-CT/assets
    - ./feedback:/app/COVIDNet-CT/feedback
    - ./interface:/app/COVIDNet-CT/interface
    - ./tests:/app/COVIDNet-CT/tests
    - /tmp/.X11-unix/:/tmp/.X11-unix
    environment:
      DISPLAY: ${DISPLAY}